remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
title: The Online Marketplace microservice benchmark
description: General information and collection of references about the Online Marketplace microservice benchmark.
